CREATE TABLE `t` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`parent_id` BIGINT UNSIGNED NOT NULL,
	`msg` TEXT NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT FOREIGN KEY(`parent_id`) REFERENCES `t` (`id`) ON DELETE CASCADE
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
