CREATE TABLE `post` (
	`a` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`b` CHAR(4) NOT NULL,
	`user_1` BIGINT UNSIGNED NOT NULL,
	`user_2` BIGINT UNSIGNED NOT NULL,
	`d` BIGINT UNSIGNED NOT NULL DEFAULT 12,
	PRIMARY KEY (`a`, `b`, `user_1`, `user_2`),
	CONSTRAINT FOREIGN KEY(`user_1`) REFERENCES `user` (`id`) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY(`user_2`) REFERENCES `user` (`id`) ON DELETE CASCADE
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
