CREATE TABLE `db_post` (
	`a` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`b` CHAR(4) NOT NULL,
	`user1` BIGINT UNSIGNED NOT NULL,
	`user2` BIGINT UNSIGNED NOT NULL,
	`d` BIGINT UNSIGNED NOT NULL DEFAULT 12,
	PRIMARY KEY (`a`, `b`, `user1`, `user2`),
	CONSTRAINT FOREIGN KEY(`user1`) REFERENCES `user` (`id`) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY(`user2`) REFERENCES `user` (`id`) ON DELETE CASCADE
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
