CREATE TABLE `t` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`id_alias` BIGINT UNSIGNED GENERATED ALWAYS AS (`id`) VIRTUAL,
	`user_id` BIGINT UNSIGNED NOT NULL,
	`user_id_alias` BIGINT UNSIGNED GENERATED ALWAYS AS (`user_id`) VIRTUAL,
	`sig` TEXT NULL DEFAULT 'def',
	`sig_alias` TEXT GENERATED ALWAYS AS (`sig`) VIRTUAL,
	PRIMARY KEY (`id`),
	CONSTRAINT FOREIGN KEY(`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
