CREATE TABLE `user` (
	`a` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`b` BIGINT UNSIGNED NOT NULL UNIQUE,
	`c` BIGINT UNSIGNED NOT NULL,
	`d` BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (`a`),
	INDEX (`c`),
	UNIQUE INDEX (`d`)
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
