CREATE TABLE `db_post` (
	`a` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`b` INT UNSIGNED NOT NULL DEFAULT 0,
	`c` INT UNSIGNED NULL DEFAULT NULL,
	`d` INT UNSIGNED NULL DEFAULT NULL,
	`e` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`a`)
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
