import VarInfo, { TypeInfo } from './lib/varInfo';

export const queryableParam = 'queryable';
export const dbParam = 'db';
export const sqlDBType = new TypeInfo('*sql.DB', 'database/sql');
export const sqlTxType = new TypeInfo('*sql.Tx', 'database/sql');
export const dbxQueryableType = new TypeInfo(
  'dbx.Queryable',
  'github.com/mgenware/go-packagex/v5/dbx',
);
export const dbxQueryableVar = new VarInfo(queryableParam, dbxQueryableType);
export const sqlDBVar = new VarInfo(dbParam, sqlDBType);
export const insertedIDKey = 'insertedID';
export const rowsAffectedKey = 'rowsAffected';
export const insertedIDVar = new VarInfo(insertedIDKey, new TypeInfo('uint64'));

export const resultVarName = 'result';
export const fileHeader = ` /${'*'.repeat(90)}
 * This code was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ${'*'.repeat(90)}/

`;
export const limitVarName = 'limit';
export const intTypeInfo = new TypeInfo('int');
export const boolTypeInfo = new TypeInfo('bool');

export const mathxNS = 'github.com/mgenware/go-packagex/v5/mathx';
